# Generated by Django 5.0.6 on 2026-02-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="ai_personality",
            field=models.TextField(
                default="You are a helpful customer support agent. Be concise and friendly.",
                help_text="Custom instructions for how the AI should respond",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="api_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
