# Generated by Django 5.0.6 on 2026-02-02 09:30

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.VectorField(dimensions=384),
        ),
    ]
