# Generated by Django 5.0.6 on 2026-02-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0002_alter_company_options_alter_company_ai_personality_and_more",
        ),
        ("knowledge", "0003_alter_documentchunk_embedding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="documentchunk",
            options={
                "ordering": ["document", "chunk_index"],
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF File"),
                    ("text", "Text File"),
                    ("markdown", "Markdown File"),
                    ("docx", "Word Document"),
                    ("csv", "CSV File"),
                    ("json", "JSON File"),
                    ("excel", "Excel File"),
                    ("paste", "Pasted Content"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="chunk_index",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["company", "status"], name="knowledge_d_company_e3faf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["company", "-created_at"], name="knowledge_d_company_57e0d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "created_at"], name="knowledge_d_status_a6ab9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="knowledge_d_documen_ea33de_idx",
            ),
        ),
    ]
