# Generated by Django 5.0.6 on 2026-02-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0002_alter_company_options_alter_company_ai_personality_and_more",
        ),
        ("conversations", "0001_initial"),
        (
            "knowledge",
            "0004_alter_document_options_alter_documentchunk_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterField(
            model_name="conversation",
            name="channel",
            field=models.CharField(
                choices=[
                    ("web", "Website Chat"),
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="customer_identifier",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resolved", "Resolved"),
                    ("handed_off", "Handed Off to Human"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("assistant", "AI Assistant"),
                    ("system", "System"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["company", "status"], name="conversatio_company_db90f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["company", "-created_at"], name="conversatio_company_7ecdb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["company", "channel", "status"],
                name="conversatio_company_909d11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["customer_identifier", "company"],
                name="conversatio_custome_d20d90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="conversatio_convers_4b968d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "role"], name="conversatio_convers_2f39c0_idx"
            ),
        ),
    ]
